### ISSUE TITLE
Problem with Ruby 1.9 Hash syntax?

### ISSUE THREAD

**Issue by Trevoke** [duskhacker/sweet-rspec-vim#11]
This plugin would be great.. But I'm getting this error, which gets in the way of my enjoyment:

```
/Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load': /Users/alg/Documents/Code/cabinet/spec/file_spec.rb:29: syntax error, unexpected ':', expecting '}' (SyntaxError)                                                                                                                        
  1       before { File.add file, fake: true }                                                                                                                                    
  2                                    ^                                                                                                                                          
  3   from /Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'                                           
  4   from /Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `each'                                                      
  5   from /Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'                                           
  6   from /Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:22:in `run'                                                         
  7   from /Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'                                                               
  8   from /Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `autorun'                                                           
  9   from /Users/alg/.rvm/gems/ruby-1.9.3-p327@cabinet/bin/ruby_noexec_wrapper:14 
```

**Comment by Trevoke** [comment]
Never mind. I hate OSX.
